First we will import data into sklearn and verify it.

In [19]:
from sklearn.datasets import load_iris

In [20]:
import numpy as np

In [21]:
iris = load_iris()

Lets print names of features

In [22]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [23]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


Lets check data, it consists details of first flower

In [24]:
print(iris.data[0])

[5.1 3.5 1.4 0.2]


Lets print out first rows target name.

In [25]:
print(iris.target[0])## Here label 0 means setosa

0


Now we can build classifier.
before that we need to split data into Training data and Testing data

In [26]:
test_idx = [0,50,100]

Training Data

In [45]:
train_target = np.delete(iris.target, test_idx)

In [46]:
train_data = np.delete(iris.data, test_idx, axis=0)

Test data

In [47]:
test_target = iris.target[test_idx]

In [48]:
test_data = iris.data[test_idx]

Lets Import Classsifiers into Program

In [49]:
from sklearn import tree

In [50]:
clf = tree.DecisionTreeClassifier()

In [51]:
clf.fit(training_data,training_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [52]:
print(test_target)

[0 1 2]


In [53]:
print(clf.predict(test_data))

[0 1 2]


Result is Similar to test data. ML program has successfully predicted flower types.